### ISSUE TITLE
Doesn't work on generated xhprof file

### ISSUE THREAD

**Issue by flip111** [sters/xhprof-html#4]
[15870816948632.zip](https://github.com/sters/xhprof-html/files/4490233/15870816948632.zip)

```php
file_put_contents(
  '/tmp/' . intval(microtime(true)) . mt_rand(1,10000) . '.xhprof',
  serialize(tideways_xhprof_disable())
);
```

**Comment by sters** [comment]
@flip111  I'm update and It works on my local env. Please use latest.

**Comment by flip111** [comment]
Thank you @sters
